In [1]:
import pandas as pd

# Load your data from the Excel file
df = pd.read_excel('neuralnet_data.xlsx')

In [2]:
# Define your custom function to map strike_rate to strike_class
def classify_high_score(high_score):
    if high_score == "teju":
        return 0
    elif 0 <= int(high_score) <= 30:
        return 1
    elif 31 <= int(high_score) <= 60:
        return 2
    elif 61 <= int(high_score) <= 90:
        return 3
    elif 91 <= int(high_score) <= 120:
        return 4
    elif 121 <= int(high_score) <= 150:
        return 5
    else:
        return 6  

def classify_not_out(not_out):
    if not_out == "teju":
        return 0
    elif 0 <= int(not_out) <= 30:
        return 1
    elif 31 <= int(not_out) <= 60:
        return 2
    elif 61 <= int(not_out) <= 90:
        return 3
    elif 91 <= int(not_out) <= 120:
        return 4
    elif 121 <= int(not_out) <= 150:
        return 5
    else:
        return 6
  

In [3]:
# Apply the custom function to create the "strike_class" column

df['high_score_class'] = df['Highest Score'].apply(classify_high_score)
df['not_out_class'] = df['Total Not Outs'].apply(classify_not_out)
# Save the DataFrame back to an Excel file if needed
df.to_excel('new_neuralnet.xlsx', index=False)

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import mean_squared_error, r2_score

# Load your data from the Excel file
data = pd.read_excel('new_neuralnet.xlsx')

# Define the features and the target variable
X = data[['Over', 'Delivery', 'high_score_class', 'strike_class', 'not_out_class']]
y = data['total_run_batter']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# Build a simple neural network
model = keras.Sequential([
    keras.layers.Dense(5, activation='relu', input_shape=(X_train.shape[1],)),
    keras.layers.Dense(1)  # Output layer with a single unit for regression
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
model.fit(X_train, y_train, epochs=20, batch_size=32, validation_split=0.2)

# Make predictions on the test data
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")


Epoch 1/20
4877/4877 [==============================] - 9s 2ms/step - loss: 777.7919 - val_loss: 586.9716
Epoch 2/20
4877/4877 [==============================] - 9s 2ms/step - loss: 579.1050 - val_loss: 576.9991
Epoch 3/20
4877/4877 [==============================] - 10s 2ms/step - loss: 573.8023 - val_loss: 573.8998
Epoch 4/20
4877/4877 [==============================] - 9s 2ms/step - loss: 572.1382 - val_loss: 572.7570
Epoch 5/20
4877/4877 [==============================] - 9s 2ms/step - loss: 571.2668 - val_loss: 572.5950
Epoch 6/20
4877/4877 [==============================] - 9s 2ms/step - loss: 570.7665 - val_loss: 571.5563
Epoch 7/20
4877/4877 [==============================] - 9s 2ms/step - loss: 570.4105 - val_loss: 571.2820
Epoch 8/20
4877/4877 [==============================] - 9s 2ms/step - loss: 570.1492 - val_loss: 571.0085
Epoch 9/20
4877/4877 [==============================] - 9s 2ms/step - loss: 569.9449 - val_loss: 572.0981
Epoch 10/20
4877/4877 [======================

In [7]:
# Load your data from the Excel file
data1 = pd.read_excel('final_result.xlsx')

In [8]:
# Make predictions using the trained model
predictions = model.predict(data1)

# Add the predictions as a new column to the DataFrame
data1['Predicted_total_run_batter'] = predictions

# Save the DataFrame with predictions to a new Excel file
data1.to_excel('final_result.xlsx', index=False)


7620/7620 [==============================] - 8s 984us/step


In [3]:
# Get the weights from the first dense layer
weights = model.layers[0].get_weights()[0]

# Convert the weights to a NumPy array
weights_array = np.array(weights)

# Print the weights
print("Weights associated with the inputs:")
print(weights_array)


Weights associated with the inputs:
[[ 0.9110675  -0.03449272  1.0922453   0.6379537  -0.6832345 ]
 [ 0.34656823 -0.7189315   0.26758012  0.02426003 -0.70526344]
 [-1.5374088   0.046777    1.6355581  -1.8444831  -0.8660773 ]
 [ 0.4858154   0.07428534  0.6507748   0.7169861   0.3320721 ]
 [ 0.42746195  0.16714458  0.35787955  0.20249411  0.17194664]]


In [4]:
# Get the weights from the output layer
output_layer_weights = model.layers[-1].get_weights()[0]

# Convert the weights to a NumPy array
output_layer_weights_array = np.array(output_layer_weights)

# Print the weights
print("Weights connecting the hidden layer to the output:")
print(output_layer_weights_array)


Weights connecting the hidden layer to the output:
[[-2.0390031 ]
 [-0.65763295]
 [ 2.231145  ]
 [-2.4533222 ]
 [ 0.27485844]]


In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import mean_squared_error, r2_score
import pickle  # Import the pickle library

# Load your data from the Excel file
data = pd.read_excel('new_neuralnet.xlsx')

# Define the features and the target variable
X = data[['Over', 'Delivery', 'high_score_class', 'strike_class', 'not_out_class']]
y = data['total_run_batter']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Build a simple neural network
model = keras.Sequential([
    keras.layers.Dense(5, activation='relu', input_shape=(X_train.shape[1],)),
    keras.layers.Dense(1)  # Output layer with a single unit for regression
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
model.fit(X_train, y_train, epochs=20, batch_size=32, validation_split=0.2)

# Make predictions on the test data
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

# Save the trained model to a pickle file
with open('neural_network_model.pkl', 'wb') as model_file:
    pickle.dump(model, model_file)


Epoch 1/20
4877/4877 [==============================] - 8s 2ms/step - loss: 706.3303 - val_loss: 583.4330
Epoch 2/20
4877/4877 [==============================] - 9s 2ms/step - loss: 576.5676 - val_loss: 575.1510
Epoch 3/20
4877/4877 [==============================] - 9s 2ms/step - loss: 572.5237 - val_loss: 573.9145
Epoch 4/20
4877/4877 [==============================] - 9s 2ms/step - loss: 571.2668 - val_loss: 572.5878
Epoch 5/20
4877/4877 [==============================] - 8s 2ms/step - loss: 570.7267 - val_loss: 572.6152
Epoch 6/20
4877/4877 [==============================] - 8s 2ms/step - loss: 570.3229 - val_loss: 571.2458
Epoch 7/20
4877/4877 [==============================] - 9s 2ms/step - loss: 570.1104 - val_loss: 571.6794
Epoch 8/20
4877/4877 [==============================] - 9s 2ms/step - loss: 569.9205 - val_loss: 572.4346
Epoch 9/20
4877/4877 [==============================] - 8s 2ms/step - loss: 569.8746 - val_loss: 570.7436
Epoch 10/20
4877/4877 [=======================

In [12]:
# Load the trained model from the pickle file
with open('neural_network_model.pkl', 'rb') as model_file:
    loaded_model = pickle.load(model_file)


In [16]:
new_data = pd.DataFrame({'Over': [1], 'Delivery': [3], 'high_score_class': [1], 'strike_class': [4], 'not_out_class': [4]})
predictions = loaded_model.predict(new_data)


1/1 [==============================] - 0s 21ms/step


In [17]:
predictions

array([[20.700699]], dtype=float32)